#!/usr/bin/env bash

# set -e

dotask (){
	for plugin in  bundle/* ; do
		pushd $plugin >/dev/null
		if [ -d ".git" ]; then
			$1
		fi
		popd >/dev/null
	done
}

function doinit (){
	list="$1"
	if [ ! -s $list ]; then
		return 1
	fi
	urls=`cat $list`
	mkdir -p undo
	mkdir -p bundle
	cd bundle
	for url in $urls; do
		git clone $url
	done
	cd ..
}

## mkdir -p ~/.vim/bundle

case $1 in
	"init" )
	if [ -n "$2" ]; then
		doinit "$2"
	else
		doinit plist
	fi
	;;

	"update" )
	dotask "git pull" ;;

	"list" )
	dotask "git config --get remote.origin.url" ;;

	"" )
	dotask "git config --get remote.origin.url" ;;

	* )
	echo "Not supported task. $1" 
	exit 1;;
esac

